#!/usr/bin/env python3
"""
judge.py — LLM analysis pass over call transcripts.

Reads each per-call transcript plus its scenario's `expected_behavior` and asks
Claude to flag CANDIDATE issues with the agent under test — each with a
timestamp, an exact quote, what happened, why it's a problem, severity, and the
judge's own confidence.

This is ASSISTIVE only. The output is an uncurated candidate list; a human
promotes the real ones into BUGS.md (the curated deliverable). The judge is told
to favor COVERAGE over precision — report everything it suspects, with confidence
levels — because a human filters downstream.

Requires:
  - pip install anthropic   (declared in requirements.txt)
  - ANTHROPIC_API_KEY in .env  — the one LLM key the harness needs beyond
    DEEPGRAM_API_KEY. The voice pipeline's LLM is Deepgram-managed and not
    usable for standalone offline analysis, so the judge calls Claude directly.

Usage:
  python judge.py --all                          # judge every calls/*.txt
  python judge.py --transcript calls/<stem>.txt  # judge one
  python judge.py --all --out CANDIDATE_BUGS.md  # aggregate destination
"""
import argparse
import glob
import json
import os
import sys
from typing import Literal

from dotenv import load_dotenv
from pydantic import BaseModel

load_dotenv()

import anthropic

from scenario_library import load_scenarios

MODEL = "claude-opus-4-8"
CALLS_DIR = "calls"
DEFAULT_OUT = "CANDIDATE_BUGS.md"


# ---------------------------------------------------------------------------
# Structured output schema
# ---------------------------------------------------------------------------

class Issue(BaseModel):
    title: str
    severity: Literal["High", "Medium", "Low"]
    confidence: Literal["high", "medium", "low"]
    timestamp: str          # MM:SS from the transcript
    quote: str              # exact line(s) from the transcript
    what_happened: str
    why_problem: str
    expected_instead: str


class JudgeResult(BaseModel):
    issues: list[Issue]
    summary: str            # one or two sentences; if no issues, say why


SYSTEM = """You are a meticulous QA analyst reviewing a recorded phone call between two parties:
  - AGENT   — an AI receptionist for a medical clinic. This is the SYSTEM UNDER TEST.
  - PATIENT — the caller. This is our own scripted test bot; do NOT report issues with the PATIENT.

Your job is to surface CANDIDATE problems with the AGENT's behavior. A human reviewer
curates your output afterward, so favor COVERAGE: report everything you suspect — including
low-confidence and low-severity items — and mark each with a confidence level. Do not filter
for importance yourself; that happens downstream.

Judge only the AGENT. Ground every issue in a specific line: give the timestamp and an exact
quote from the transcript. If the AGENT behaved correctly throughout, return an empty issues
list and explain why in the summary."""


def build_user_prompt(scenario_id: str, expected_behavior: str | None, transcript: str) -> str:
    expected = expected_behavior or (
        "(no scenario on file for this call — judge against general correct "
        "medical-receptionist behavior)"
    )
    return f"""SCENARIO: {scenario_id}

WHAT A CORRECT AGENT SHOULD DO (expected behavior for this scenario):
{expected}

TRANSCRIPT (timestamps are MM:SS; AGENT = system under test, PATIENT = our test caller):
{transcript}

Flag candidate issues with the AGENT. For each: a one-line title, severity
(High/Medium/Low), your confidence (high/medium/low), the timestamp, the exact quote,
what happened, why it's a problem, and what the agent should have done instead."""


def judge_transcript(client, scenario_id, expected_behavior, transcript) -> JudgeResult:
    message = client.messages.parse(
        model=MODEL,
        max_tokens=16000,
        thinking={"type": "adaptive"},
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": build_user_prompt(scenario_id, expected_behavior, transcript),
        }],
        output_format=JudgeResult,
    )
    return message.parsed_output


def render_markdown(results: list[dict]) -> str:
    lines = [
        "# Candidate Bugs — judge pass (assistive, uncurated)",
        "",
        "Auto-generated by `judge.py`. These are *candidates*: a human promotes the real",
        "ones into `BUGS.md`. Each is tagged with the judge's confidence so low-signal items",
        "can be skipped quickly.",
    ]
    for r in results:
        res: JudgeResult = r["result"]
        lines.append(f"\n## {r['stem']}  (scenario: {r['scenario_id']})\n")
        if not res.issues:
            lines.append(f"_No issues flagged. {res.summary}_")
            continue
        lines.append(f"_{res.summary}_\n")
        for i in res.issues:
            lines.append(
                f"- **[{i.severity} · conf {i.confidence}] {i.title}**\n"
                f"  - Call: `calls/{r['stem']}.txt` at `{i.timestamp}`\n"
                f"  - Quote: \"{i.quote}\"\n"
                f"  - What happened: {i.what_happened}\n"
                f"  - Why it's a problem: {i.why_problem}\n"
                f"  - Expected instead: {i.expected_instead}"
            )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="LLM judge pass over call transcripts")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--all", action="store_true", help="Judge every calls/*.txt")
    group.add_argument("--transcript", help="Judge a single transcript file")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"Aggregate markdown output (default {DEFAULT_OUT})")
    args = parser.parse_args()

    if not os.getenv("ANTHROPIC_API_KEY"):
        print("ERROR: ANTHROPIC_API_KEY is not set. Add it to .env — the judge calls Claude.")
        sys.exit(1)

    transcripts = (
        sorted(glob.glob(os.path.join(CALLS_DIR, "*.txt")))
        if args.all else [args.transcript]
    )
    if not transcripts:
        print(f"No transcripts found in {CALLS_DIR}/. Run some calls first.")
        sys.exit(1)

    client = anthropic.Anthropic()
    scenarios_by_id = {s["scenario_id"]: s for s in load_scenarios()}

    results = []
    for path in transcripts:
        stem = os.path.splitext(os.path.basename(path))[0]
        scenario_id = stem.split("__", 1)[0]  # <scenario_id>__<call_sid>
        expected = (scenarios_by_id.get(scenario_id) or {}).get("expected_behavior")
        transcript = open(path, encoding="utf-8").read()

        print(f"judging {stem} (scenario={scenario_id})...", flush=True)
        result = judge_transcript(client, scenario_id, expected, transcript)

        # Per-call machine-readable candidates, aligned with the call's other artifacts.
        json_path = os.path.join(CALLS_DIR, f"{stem}.candidates.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(result.model_dump(), f, indent=2)

        print(f"  -> {len(result.issues)} candidate issue(s); wrote {json_path}")
        results.append({"stem": stem, "scenario_id": scenario_id, "result": result})

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(render_markdown(results))

    total = sum(len(r["result"].issues) for r in results)
    print(f"\n{total} candidate issue(s) across {len(results)} call(s) -> {args.out}")


if __name__ == "__main__":
    main()
